[project]
name = "sasantlerparser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "antlr4-python3-runtime>=4.13.2",
    "tqdm>=4.67.3",
]
